---
title: First post
author: ''
date: '2020-06-07'
slug: first-post
categories:
  - R
tags: []
---

```{r setup,echo=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```

## Describe a model: 

The first step is to create a simulated dataset, which mimics real transitions for an undergraduate student. 

```{r createSimulation}

library(tidyverse)
library(rsample)
library(markovchain)

Simulated = tibble(Id = seq(1, 100, 1),
                   Semester = rep(c("F", "W"),50),
                   NumberSemester = rep(1:4, 25)) %>% 
  expand(Id, Semester, NumberSemester) %>% 
  arrange(Id, NumberSemester, Semester) 

Simulated2 = Simulated %>% 
  mutate(ProbOfMovingOn = runif(dim(Simulated)[1], 0,1),
         MovedOn = case_when(ProbOfMovingOn > .1 ~ 1, TRUE ~ 0) ,
         CurrentSemester= case_when( MovedOn == 1 ~ paste0(Semester, NumberSemester), TRUE ~ "Leave")) %>% 
  group_by(Id) %>% 
  mutate(FutureSemester = lead(CurrentSemester)) %>% 
  ungroup() 
  

```


The next step is to simulate the chances of moving on. 

```{r ShowData}

knitr::kable(head(Simulated2))

```
